language: php
php:
  - 7.2
  - 7.3
  - 7.4
env:
  - COMPOSER_MEMORY_LIMIT=-1 COMPOSER_MIRROR_PATH_REPOS=1
before_install:
  - cd ~
  - composer create-project chirripo/drupal-template testchirripo --stability stable --no-interaction
  - cd testchirripo
  - echo "PROJECT_ROOT=~/testchirripo" >> .env
  - composer install
  - cd $TRAVIS_BUILD_DIR
  - composer install
  - ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa <<< y
before_script:
  - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH

script:
  - cd ~/testchirripo
  - chirripo --version
  - chirripo ps
